/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author Garay_Ruiz
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setSize(852, 524);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTituloCentro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        imgavion = new javax.swing.JLabel();
        btnCrearReserva = new javax.swing.JButton();
        btnBuscarVuelo = new javax.swing.JButton();
        btnConsultarIte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        encabezado.setBackground(new java.awt.Color(204, 204, 204));

        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Sistema de Gestión de Vuelos ");

        javax.swing.GroupLayout encabezadoLayout = new javax.swing.GroupLayout(encabezado);
        encabezado.setLayout(encabezadoLayout);
        encabezadoLayout.setHorizontalGroup(
            encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encabezadoLayout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(lblTitulo)
                .addContainerGap(476, Short.MAX_VALUE))
        );
        encabezadoLayout.setVerticalGroup(
            encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encabezadoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addContainerGap())
        );

        getContentPane().add(encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblTituloCentro.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblTituloCentro.setForeground(new java.awt.Color(0, 110, 255));
        lblTituloCentro.setText("SISTEMA DE VUELOS ");
        getContentPane().add(lblTituloCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, 50));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("GESTIONA TUS VUELOS DE MANERA EFICIENTE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, 30));

        imgavion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/avion60x60.png"))); // NOI18N
        getContentPane().add(imgavion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 110, 60));

        btnCrearReserva.setBackground(new java.awt.Color(0, 102, 255));
        btnCrearReserva.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnCrearReserva.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notas30x30.png"))); // NOI18N
        btnCrearReserva.setText("CREAR RESERVA");
        btnCrearReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearReservaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 240, -1));

        btnBuscarVuelo.setBackground(new java.awt.Color(204, 153, 0));
        btnBuscarVuelo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnBuscarVuelo.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarVuelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa30x30.png"))); // NOI18N
        btnBuscarVuelo.setText("BUSCAR VUELO");
        btnBuscarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVueloActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 240, -1));

        btnConsultarIte.setBackground(new java.awt.Color(0, 153, 51));
        btnConsultarIte.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnConsultarIte.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarIte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libro30X30.png"))); // NOI18N
        btnConsultarIte.setText("CONSULTAR ITINERARIO");
        getContentPane().add(btnConsultarIte, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 240, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarVueloActionPerformed

    private void btnCrearReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearReservaActionPerformed
        // TODO add your handling code here:
        FrmCrearReserva principal = new FrmCrearReserva();
        principal.setLocationRelativeTo(null);
        principal.setVisible(true);
        
    }//GEN-LAST:event_btnCrearReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarVuelo;
    private javax.swing.JButton btnConsultarIte;
    private javax.swing.JButton btnCrearReserva;
    private javax.swing.JPanel encabezado;
    private javax.swing.JLabel imgavion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloCentro;
    // End of variables declaration//GEN-END:variables
}
